### ISSUE TITLE
Reference the contributing.md in the readme

### ISSUE THREAD

**Issue by SisiVero** [SisiVero/CC-guides#11]
In the readme, currently, readers do not know that they can contribute to this repo.

In the README.md, reference the CONTRIBUTING.md file, this will let the readers know that they can contribute to the repo.
You ca check other repos: legalb to see an instance.

As seen in legalddB README.md:
<img width="373" alt="contributgMD" src="https://github.com/user-attachments/assets/e739e121-a2b9-4ee0-b579-360ecb935f28">

**Comment by lauracastrotech** [comment]
@SisiVero I can do this!
