### ISSUE TITLE
docs: add a simple contribution.md guide

### ISSUE THREAD

**Issue by FatumaA** [SisiVero/CC-guides#2]
Hi, 
I think adding a simple contribution guide on how to make changes or add resources to this repo would be useful

**Comment by lauracastrotech** [comment]
@FatumaA i'd love to take this on, what do you think about the following:
1. Fork the repo
2. Clone it to your local machine
3. Add resources by creating an md, or adding links to existing documentation
4. format it
5. create a pull request with a description that 1-3 sentences
6. wait for feedback and  make changes accordingly

**Comment by FatumaA** [comment]
Hi Laura,
That won't be necessary, as I've already made a PR with the guide and linked it above. 
Thank you :)

**Comment by lauracastrotech** [comment]
Oh I see you're waiting for the PR to be reviewed. At that point the issue will close or be resolved, right?
